AMQP_URL=${AMQP_URL}
ELMA365_AMQP_URL=${ELMA365_AMQP_URL}
ELMA365_MONGO_DB_NAME=${ELMA365_MONGO_DB_NAME}
ELMA365_MONGO_PASSWORD=${ELMA365_MONGO_PASSWORD}
ELMA365_MONGO_USER=${ELMA365_MONGO_USER}
ELMA365_POSTGRES_DB_NAME=${ELMA365_POSTGRES_DB_NAME}
ELMA365_POSTGRES_PASSWORD=${ELMA365_POSTGRES_PASSWORD}
ELMA365_POSTGRES_USER=${ELMA365_POSTGRES_USER}
ELMA365_RABBITMQ_HOST=${ELMA365_RABBITMQ_HOST}
ELMA365_RABBITMQ_PASSWORD=${ELMA365_RABBITMQ_PASSWORD}
ELMA365_RABBITMQ_USER=${ELMA365_RABBITMQ_USER}
ELMA365_RABBITMQ_VH_NAME=${ELMA365_RABBITMQ_VH_NAME}
MONGO_URL=${MONGO_URL}
PSQL_URL=${PSQL_URL}
REDIS_URL=${REDIS_URL}
RO_POSTGRES_URL=${RO_POSTGRES_URL}
S3_BACKEND_ADDRESS=${S3_BACKEND_ADDRESS}
S3_KEY=${S3_KEY}
S3_REGION=${S3_REGION}
S3_SECRET=${S3_SECRET}
S3_SSL_ENABLED=${S3_SSL_ENABLED}
S3_UPLOAD_METHOD=${S3_UPLOAD_METHOD}
VAHTER_MONGO_URL=${VAHTER_MONGO_URL}
